-- Add new customization fields to stores table
ALTER TABLE public.stores 
ADD COLUMN IF NOT EXISTS accent_color TEXT DEFAULT '#2F1810',
ADD COLUMN IF NOT EXISTS welcome_message TEXT,
ADD COLUMN IF NOT EXISTS announcement_text TEXT,
ADD COLUMN IF NOT EXISTS announcement_active BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS show_reviews BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS show_stock BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'MXN',
ADD COLUMN IF NOT EXISTS tax_rate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS min_order_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS store_timezone TEXT DEFAULT 'America/Mexico_City',
ADD COLUMN IF NOT EXISTS twitter_url TEXT,
ADD COLUMN IF NOT EXISTS tiktok_url TEXT,
ADD COLUMN IF NOT EXISTS website_url TEXT,
ADD COLUMN IF NOT EXISTS return_policy TEXT,
ADD COLUMN IF NOT EXISTS shipping_info TEXT;